config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  resources :users do
    resources :animals do
      collection do
        get :next_show
      end
      resources :foodbrands
    end
    resources :appointments
  end
  resources :vets

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  delete '/session/', to: 'sessions#destroy'
end

app/models/animal.rb
# frozen_string_literal: true

class Animal < ActiveRecord::Base
  has_many :foodbrands
  belongs_to :user

  validates :name, presence: true
  validates :weight, presence: true
  validates :breed, presence: true
  validates :age, presence: true
  scope :users_animals, ->(user) { where(user: user) }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ActiveRecord::Base
  belongs_to :user
  belongs_to :vet
  validates :date, presence: true
  validates :time, presence: true
end

app/models/foodbrand.rb
# frozen_string_literal: true

class Foodbrand < ApplicationRecord
  belongs_to :animal
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  has_secure_password
  has_many :animals
  has_many :appointments
  has_many :vets, through: :appointments
  validates :name, :email, :password, presence: true
  validates :email, uniqueness: true
end

app/models/vet.rb
# frozen_string_literal: true

class Vet < ActiveRecord::Base
  has_many :appointments
  has_many :users, through: :appointments
end

app/controllers/animals_controller.rb
# frozen_string_literal: true

class AnimalsController < ApplicationController
  before_action :set_animal, except: %i[new index]

  def index
    @animals = Animal.users_animals(current_user)

    respond_to do |format|
      format.html { render "animals/index" }
      format.json { render json: @animals.to_json(only: [:name]) }
    end
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = current_user.animals.build(animal_params)
    if @animal.save
      redirect_to user_animals_path(current_user)
    else
      render :new
    end
  end

  def edit
    @animal = Animal.find_by(id: params[:id])
  end

  def next_show
    @animal = Animal.find_by(id: params[:id])
    @foodbrand = Foodbrand.new

    respond_to do |format|
      format.json do
        render json: @animal.to_json(only: %i[name description weight],
                                     include: [foodbrand: { only: [:name] }])
      end
    end
  end

  def show
    @animal = Animal.find_by(id: params[:id])
    @next_animal = next_or_previous_animal_for(@animal)
    @foodbrand = Foodbrand.new
  end

private

  def animal_params
    params.require(:animal).permit(:name, :breed, :age, :description, :weight)
  end

  def set_animal
    @animal = Animal.find(params[:user_id])
  end

  def next_or_previous_animal_for(current_animal)
    users_animals = Animal.where(user: current_user)
    users_animals.find_by(
      "id > :current_animal_id",
      current_animal_id: current_animal.id
    ) || users_animals.first
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def current_user
    User.find(session[:user_id])
  end

  def user_signed_in?
    true if session[:user_id]
  end
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < ApplicationController
  # before_action :verify_login

  def index
    @appointments = User.find_by(id: current_user.id).appointments
  end

  def show
    @appointment = Appointment.find_by(params[:id])
  end

  def create
    @appointment = current_user.appointments.build(appointment_params)
    if @appointment.save
      redirect_to user_appointments_path(current_user)
    else
      render :new
    end
  end

  def new
    @appointment = Appointment.new
  end

  def destroy
    @appointment = Appointment.find_by(id: params[:id])
    @appointment.destroy
    redirect_to user_appointments_path(current_user)
  end

private

  def appointment_params
    params.require(:appointment).permit(:date, :time, :vet_id)
  end
end

app/controllers/foodbrands_controller.rb
# frozen_string_literal: true

class FoodbrandsController < ApplicationController
  def create
    @animal = Animal.find_by(id: params[:animal_id])
    @foodbrand = @animal.foodbrands.build(foodbrand_params)
    if @foodbrand.save
      respond_to do |format|
        format.json { render json: @foodbrand.to_json(only: [:name]) }
      end
    else
      render "animals/show"
    end
  end

private

  def foodbrand_params
    params.require(:foodbrand).permit(:name)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    if user_signed_in?
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    user = User.find_by(email: params[:user][:email])
    user.try(:authenticate, params[:user][:password])
    @user = user
    session[:user_id] = @user.id
    redirect_to user_path(@user), notice: "Thanks for signing in"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

private

  def user_params
    params[:user]
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    if user_signed_in?
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end

  def show; end

  def create
    if passwords_match?
      @user = User.create!(user_params)
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to new_user_path
    end
  end

private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end

  def passwords_match?
    params[:user][:password] == params[:user][:password_confirmation]
  end
end

app/controllers/vets_controller.rb
# frozen_string_literal: true

class VetsController < ApplicationController
end

app/helpers/animals_helper.rb
# frozen_string_literal: true

module AnimalsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_user
    User.find(session[:user_id])
  end

  def user_signed_in?
    true if session[:user_id]
  end

  def form_errors_for(object = nil)
    render("shared/form_errors", object: object) unless object.blank?
  end
end

app/helpers/appointments_helper.rb
# frozen_string_literal: true

module AppointmentsHelper
end

app/helpers/vets_helper.rb
# frozen_string_literal: true

module VetsHelper
end

app/views/animals/edit.html.erb
<% current_user.animals.each do |animal| %>
    <ol>
      <h3><%= animal.name %></h3>
    </ol>
    <p><%= animal.description %></p>
  <% end %>

app/views/animals/index.html.erb
<h1><b><%= current_user.name %>'s Pets:</b></h1>
<% if current_user.animals.none? %>
    <p>There are currently no pets on your file.</p>
    <br>
  <% else %>
  Select the pet you want more information on:
  <br>
  <br>
    <% current_user.animals.each do |animal| %>
      <ol>
      <h3><%= link_to animal.name, user_animal_path(current_user, animal) %></h3>
      </ol>
    <% end %>
  <% end %>
  <br>
<i>New member of the family? Click <%= link_to "here", new_user_animal_path(current_user) %> to tell us about your new friend!</i>
<br>
<br>
<b>or</b>
<br>
<br>
Return <%= link_to "home", user_path(current_user) %>

app/views/animals/new.html.erb
<h1><b>So you got a new pet...</b></h1>
<h3><i>Tell us more!</i></h3><br>
<%= form_for [current_user, @animal] do |animal| %>
<%= form_errors_for @animal %>
  <% animal_types = ['cat', 'dog', 'other'] %>
  <% animal_types.each do |species| %>
    <%= animal.label species %>
    <%= animal.check_box :species, {multiple: true}, species %>
  <% end %>
  <br>
  <%= animal.label "name" %>:
  <%= animal.text_field :name %><br />
  <%= animal.label "Breed/Species" %>:
  <%= animal.text_field :breed %><br />
  <%= animal.label "age" %>:
  <%= animal.number_field :age %> years<br />
  <%= animal.label "weight" %>:
  <%= animal.text_field :weight %> lbs<br />
  <%= animal.label "description" %>:
  <%= animal.text_field :description %><br />
  <br>
  <%= animal.submit "Create New Animal" %>
<% end %>

app/views/animals/show.html.erb
<h1><b><%= @animal.name %></b>...<i>the <%= @animal.breed %></i>!</h1>
<br>
<h2><%= @animal.name %> is...</h2>
<p><i><%= @animal.description %></i></p>
<br>
<br>
<h3><strong>Weight:</h3></strong><%= @animal.weight %> lbs
<br>
<br>
<br>
<br>
<strong>What's your pet's favorite food brand?</strong>
<br>
<br>
  <ol id="foodbrands_list">
    <% @animal.foodbrands.each do |brand| %>
      <li><%= brand.name %></li>
    <% end %>
  </ol>
<br>
<%= form_for [current_user, @animal, @foodbrand] do |foodbrand| %>
  <%= foodbrand.label "Food Brand" %>:
  <%= foodbrand.text_field :name %><br />
  <%= foodbrand.submit "Add Food", id: "foodbrand_submit", data: { turbolinks: "false" } %>
  <% end %>
  <br>
 Next <%= link_to "animal", user_animal_path(current_user, @next_animal) %>
<br>
<br>
<br>
Go <%= link_to "back", user_animals_path(current_user) %>

app/views/appointments/edit.html.erb
<% if current_user.appointments.none? %>
    <b><i> You have no pending appointments.</i></b>
<% end %>
<% current_user.appointments.each do |appointment| %>
<ol>
<h2><%= link_to appointment.date.strftime("%B %d, %Y") %></h2> at
<%= appointment.time.strftime("%l %P") %><br>
 with Dr.
<%= appointment.vet.name %>
</ol>
<% end %>

app/views/appointments/index.html.erb
<h2><b>Current Appointments:</b></h2>
If you need to cancel an appointment, please select it below:
<br>
<br>
<% if current_user.appointments.none? %>
<b><i> You have no pending appointments.</i></b>
<% end %>
<tr>
<% current_user.appointments.each do |appointment| %>
  <%= link_to appointment.date.strftime("%B %d, %Y"), user_appointment_path(current_user, appointment)%><br>
  <b>at <%= appointment.time.strftime("%l %P") %></b><br>
  <i>with Dr. <%= appointment.vet.name %></i><br><br>
</tr>
<% end %>
<br>
<br>
To schedule a new appointment, click <%= link_to "here", new_user_appointment_path(current_user) %>.

app/views/appointments/new.html.erb
<h1>Schedule New Appointment Below:</h1><br>
<%= form_for [current_user, @appointment] do |appointment| %>
<%= form_errors_for @appointment %>
  <%= appointment.label "Date" %>:
  <%= appointment.date_select :date %><br />
  <%= appointment.label "Time" %>:
  <%= appointment.time_select :time, {ampm: true, ignore_seconds: true, minute_step: 15, start_hour: 8, end_hour: 17} %><br />
  <%= appointment.label "Select a Vet:" %><br>
  <%= appointment.collection_select(:vet_id, Vet.all, :id, :name) %><br>
  <br>
  <%= appointment.submit "Create New Appointment" %>
<% end %>

app/views/appointments/show.html.erb
<h3><b><%= @appointment.date.strftime("%B %d, %Y") %></b></h3>
<i>at <%= @appointment.time.strftime("%l %P") %> with Dr. <%= @appointment.vet.name %></i>
<br>
<br>
<br>
<h3><i>Can't make this appointment?</i></h3>
<%= button_to 'Cancel', user_appointment_path(@appointment.id), :method => :delete, :confirm => 'Are you sure?' %>
<br>
<br>
<i>or</i>
<br>
Go back to view your <%= link_to "current appointments", user_appointments_path(current_user) %>.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Rails Veterinary Services</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar">
      <div class="container">
        <a class="navbar-brand logo">Rails Veterinary Services</a>
          <ul class="nav navbar-nav ml-auto">
            <% if user_signed_in? %>
             <li role="presentation"><%= link_to "Home", user_path(current_user), class: "nav-item nav-link active" %></a>
              </li>
              <li role="presentation"><%= link_to "My Pets", user_animals_path(current_user), class: "nav-item nav-link active" %></a>
              </li>
              <li role="presentation"><%= link_to "My Appointments", user_appointments_path(current_user), class: "nav-item nav-link active" %></a>
              </li>
              <li role="presentation"><%= link_to "Logout", logout_path, class: "nav-item nav-link active" %></a></li>
          <% else %>
            <li role="presentation"><%= link_to "Login", login_path, class: "nav-item nav-link active" %></a>
          </li>
          <li role="presentation"><%= link_to "Signup", new_user_path, class: "nav-item nav-link active" %></a>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</nav>
<main class="page">
<section class="clean-block" style="background-color:rgba(0, 255, 0, 0.3);">
  <div class="container clean-block">
    <br>
    <% if :form_errors %>
    <%= yield :form_errors %>
    <% end %>
    <%= yield %>
    <div class="block-heading"></div>
  </div>
</section>
</main>
<footer class="page-footer dark">
<div class="footer-copyright">
  <p>© 2018 Copyright Rails Veterinary Services</p>
</div>
</footer>
</body>

</html>

app/views/shared/_form_errors.html.erb
<% content_for :form_errors do %>
<% if object.errors.any? %>
  <p>
    <%= pluralize(object.errors.count, "error") %> prevented the form from being saved:
  </p>

  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
<% end %>

app/views/static_pages/home.html.erb
<h1>Welcome to Rails Veterinary Services!</h1><br>
<h3>Please <%= link_to "login", login_path %> or <%= link_to "sign up", new_user_path %> to get started.</h3>
<% yield %>

app/views/users/new.html.erb
<h2>Please Sign Up To Continue:</h2>
<br>
<%= form_for @user do |f| %>
<%= form_errors_for @user %>
<%= f.label "Name:" %>
<%= f.text_field :name, required: true %>
<br>
<%= f.label "E-mail:" %>
<%= f.text_field :email, required: true %>
<br>
<%= f.label "Password:" %>
<%= f.password_field :password, required: true %>
<br>
<%= f.label "Confirm Password:" %>
<%= f.password_field :password_confirmation, required: true %>
<br>
<br>
<%= f.submit "Submit" %>
 <% end %>

app/views/users/show.html.erb
<h1>Hello, <b><%= current_user.name %>!</b></h1>
<p>Click <%= link_to "here", user_animals_path(current_user), :class => "load_animals" %> to see your pets.</p>
  <br>
  <ol id="animals_list">

  </ol>
  <br>
<h3>Upcoming Appointment:</h3>
<% if current_user.appointments.none? %>
    <i>You have no pending appointments.</i>
    <br>
    <br>
    <br>
    <i>Need to schedule a visit? Click <%= link_to "here", new_user_appointment_path(current_user) %>.</i><br>
<% end %>
<% current_user.appointments.each do |appointment| %>
    <%= appointment.date.strftime("%B %d, %Y") %>
    <br>
    at <%= appointment.time.strftime("%l %P") %> with Dr. <%= appointment.vet.name %>
    <br>
    <br>
    <br>
    <br>
    <br>
<% end %>
<br>
<br>
    <h2><b>We get it.</b> <i>Life happens.</i></h2>
    <p>If something came up and you can no longer make your appointment, please <%= link_to "let us know.", user_appointments_path(current_user) %></p>